---
###
# Variables here apply to both production and development
# Variables set here will override settings in roles/defaults
# Variables set here will ALSO override settings in hosts!
###

# we assume the ansibleuser exists and has sudo access
ansibleuser: deploy
opentree_user: deploy
adminuser: admin
synthesis_local: False

phylesystem_repo: phylesystem-1
collections_repo: collections-1

# default python version
python_version: python3.7

# python virtualenvs
venv_otcws: /home/{{ansibleuser}}/venv_otcws
venv_synth: /home/{{ansibleuser}}/venv_synth
venv_web2py: /home/{{opentree_user}}/venv_web2py

# directories
# these all get created in /home/{{ansibleuser}}
repo_dir: /home/{{ansibleuser}}/repos
ot_repo_dir: /home/{{opentree_user}}/repos
cpp_apps_dir: /home/{{ansibleuser}}/cpp_apps
ws_dir: /home/{{ansibleuser}}/ws_dir
otc_ws_data: "{{ ws_dir }}/otc_ws_data"
synth_dir: /home/{{ansibleuser}}/synth
downloads_dir: /home/{{ansibleuser}}/downloads
unpacked_dir: /home/{{ansibleuser}}/unpacked
logfile_dir: /home/{{ansibleuser}}/logs


peyotl_git_remote: https://github.com/OpenTreeOfLife/peyotl
peyotl_webapp_branch: master

# Synthesis tree and open tree taxonomy download locations
# Set versions in production.yml, development.yml, or nexttree.yml
files_url: https://files.opentreeoflife.org
synth_tree_url: "{{ files_url }}/synthesis/opentree{{ synth_version }}/opentree{{synth_version}}.tgz"
ott_url: "{{ files_url }}/ott/ott{{ ott_version }}/ott{{ ott_version }}.tgz"

# where should Apache send requests that have not previously matched elsewhere?
apache_default_web_destination: None

deploy_custom_synth: false

# By default, curation on tree
curator_endpoint: https://tree.opentreeoflife.org/curator
study_api_endpoint: https://api.opentreeoflife.org
study_index_endpoint: https://otindex.opentreeoflife.org
study_index_endpoint_cache: https://otindex.opentreeoflife.org
