---
###
# Variables here apply to both production and development
# Variables set here will override settings in roles/defaults
###

# we assume the ansibleuser exists and has sudo access
ansibleuser: deploy
adminuser: admin
#opentree_maven_dir: /home/{{ansibleuser}}/.m2/repository/org/opentree

# python virtualenvs
#venv_otcws: /home/{{ansibleuser}}/venv_otcws
venv_web2py: /home/{{ansibleuser}}/venv_web2py

# directories
# these all get created in /home/{{ansibleuser}}
repo_dir: repos
cpp_apps_dir: cpp_apps
#ws_dir: /home/{{ansibleuser}}/ws
#users_bin_dir: /home/{{ansibleuser}}/bin
#web2py_dir: /home/{{ansibleuser}}/web2py
downloads_dir: /home/{{ansibleuser}}/downloads
unpacked_dir: /home/{{ansibleuser}}/unpacked
logfile_dir: /home/{{ansibleuser}}/logs


peyotl_git_remote: https://github.com/OpenTreeOfLife/peyotl
peyotl_webapp_branch: master

# Synthesis tree and open tree taxonomy download locations
# Set versions in production.yml, development.yml, or nexttree.yml
files_url: https://files.opentreeoflife.org
synth_tree_url: "{{ files_url }}/synthesis/opentree{{ synth_version }}/opentree{{synth_version}}.tgz"
ott_url: "{{ files_url }}/ott/ott{{ ott_version }}/ott{{ ott_version }}.tgz"

# otcetera_git_remote: https://github.com/OpenTreeOfLife/otcetera
# otcetera_synth_branch: bump_fossil_higher
# otcetera_ws_branch: no-fuzzy-match-db

ws_wrapper_git_remote: https://github.com/OpenTreeOfLife/ws_wrapper
ws_wrapper_branch: master

otc_ws_data: /home/{{ansibleuser}}/ws/otc_ws_data

#opentree_branch: nexttree
