---
normaluser: opentree
adminuser: admin
venv_synth: /home/{{normaluser}}/venv_synth
venv_otcws: /home/{{normaluser}}/venv_otcws
repo_dir: /home/{{normaluser}}/repo
synth_dir: /home/{{normaluser}}/synth
ws_dir: /home/{{normaluser}}/ws
taxomachine_neo4j_dir: /home/{{normaluser}}/neo4j-taxomachine
# treemachine_neo4j_dir: /home/{{normaluser}}/neo4j-treemachine
# oti_neo4j_dir: /home/{{normaluser}}/neo4j-oti
downloads_dir: /home/{{normaluser}}/downloads
unpacked_dir: /home/{{normaluser}}/unpacked

peyotl_git_remote: https://github.com/mtholder/peyotl

# next_synth_version should not be hard-coded
next_synth_version: 10.4

otcetera_git_remote: https://github.com/mtholder/otcetera
otcetera_synth_branch: nexttree
otcetera_ws_branch: master

taxomachine_git_remote: https://github.com/OpenTreeOfLife/taxomachine
taxomachine_branch: master

ws_wrapper_git_remote: https://github.com/OpenTreeOfLife/ws_wrapper
ws_wrapper_branch: master

ott_synth_full_version: ott3.0draft6
ott_version: ott3.0

otc_ws_data: /home/{{normaluser}}/ws/otc_ws_data
