---
normaluser: opentree
adminuser: admin
venv_synth: /home/{{normaluser}}/venv_synth
venv_otcws: /home/{{normaluser}}/venv_otcws
synth_dir: /home/{{normaluser}}/synth
ws_dir: /home/{{normaluser}}/ws
# next_synth_version should not be hard-coded
next_synth_version: 10.4
otcetera_synth_branch: nexttree
otcetera_ws_branch: master
otcetera_git_remote: https://github.com/mtholder/otcetera
ott_synth_full_version: ott3.0draft6
ott_version: ott3.0
otc_ws_data: /home/{{normaluser}}/ws/otc_ws_data
