---
# variables for development servers
# Variables set here will override settings in roles/defaults

synth_version: 13.4
ott_version: 3.3
phylesystem_repo: phylesystem-1

taxonomy_endpoint:  https://api.opentreeoflife.org
conflict_endpoint:  https://api.opentreeoflife.org
taxonomy_endpoint_cache:  https://api.opentreeoflife.org
tree_of_life_endpoint:  https://api.opentreeoflife.org
tree_of_life_endpoint_cache:  https://api.opentreeoflife.org

peyotl_otc_ws_branch: master
ws_wrapper_branch: chronosynth
ws_dir: /home/{{ansibleuser}}/ws_dir
chronosynth_branch: dev


otcetera_git_remote: https://github.com/OpenTreeOfLife/otcetera
# otcetera_synth_branch: development
otcetera_branch: development
