---
# variables for development servers
# Variables set here will override settings in roles/defaults

synth_version: 13.4
ott_version: 3.3
phylesystem_repo: phylesystem-0


subdomain: devapi # in production, this would be api
tree_of_life_endpoint: https://{{ subdomain }}.opentreeoflife.org
tree_of_life_endpoint_cache: https://{{ subdomain }}.opentreeoflife.org
taxonomy_endpoint:  https://{{ subdomain }}.opentreeoflife.org
taxonomy_endpoint_cache:  https://{{ subdomain }}.opentreeoflife.org
conflict_endpoint:  https://{{ subdomain }}.opentreeoflife.org
otindex_endpoint:  https://{{ subdomain }}.opentreeoflife.org
study_api_endpoint: https://{{ subdomain }}.opentreeoflife.org



phylesystem_api_stub: devphylesystemapi
otindex_stub: devotindex