---
# variables for devphylesystemapi server
# Variables set here will override settings in role/*/defaults/main.yml

synth_version: 13.4
ott_version: 3.3

phylesystem_api_branch: tag-fix

# these allow us to specify the SSH keys that git pushes
# will use. Leave the config keys in this config file,
# without any values assigned, to not use this feature
## Need to generate key on server, 
## and set in GitHub as deploy key for appropriate app.
git_ssh: "{{ install_dir }}/phylesystem-api/bin/git.sh"
git_private_key: "/home/{{ ansibleuser }}/.ssh/id_ed25519_shared"




# NB - all public APIs move through a common base URL
#   (typically `devapi` for development, `api` for production)
apis_common_base_URL: https://devapi.opentreeoflife.org
# Some development systems also look to production data
apis_production_base_URL: https://api.opentreeoflife.org



# other API endpoints
collections_api_base_url: "https://{{ apis_common_base_URL }}/"
amendments_api_base_url: "https://{{ apis_common_base_URL }}/"
favorites_api_base_url: "https://{{ apis_common_base_URL }}/"
otindex_base_url: "https://{{ apis_common_base_URL }}/"

# Github repo org+name for each docstore repo
#
STUDIES_GITHUB_NAME: phylesystem-0
COLLECTIONS_GITHUB_NAME: collections-0
AMENDMENTS_GITHUB_NAME: amendments-0
