---
# variables for nexttree server
# Variables set here will override settings in role/*/defaults/main.yml

synth_version: 12.3
ott_version: 3.2
phylesystem_repo: phylesystem-1
otcetera_synth_branch: master

# if True, install the webapp with curation disabled
deploy_type: curatorless

# all of the synthesis repos and data in synth_dir and all of the
# web services repos and data in ws_dir
synth_dir: /home/{{ansibleuser}}/synthesis
ws_dir: /home/{{ansibleuser}}/ws_dir
cpp_apps_dir: "{{ ws_dir }}/cpp_apps"
otc_ws_data: "{{ ws_dir }}/data"

# virtualenv for various ws components
venv_otcws: "{{ ws_dir }}/venv_otcws"

# These next two control whether you are building a new synthetic tree
# and whether to copy the synthesis tree + OTT from synth_dir or download
# them from files server. If build_synthesis is True, ignores synthesis_local
build_synthesis: False
synthesis_local: False

# URLs for external API calls; nextree runs its own tree and ott webservices
# but calls production services for phylesystem-api and otindex
otindex_url: https://otindex.opentreeoflife.org
phylapi_url: https://phylesystemapi.opentreeoflife.org
