---
# Variables for production servers
# Values set here will override settings in roles/defaults

synth_version: 12.3
ott_version: 3.2
phylesystem_repo: phylesystem-1

curator_endpoint: https://tree.opentreeoflife.org/curator
taxonomy_endpoint:  https://api.opentreeoflife.org
taxonomy_endpoint_cache:  https://api.opentreeoflife.org
tree_of_life_endpoint:  https://api.opentreeoflife.org
tree_of_life_endpoint_cache:  https://api.opentreeoflife.org
study_api_endpoint: https://phylesystemapi.opentreeoflife.org
study_index_endpoint: https://otindex.opentreeoflife.org
study_index_endpoint_cache: https://otindex.opentreeoflife.org
