---

- name: Clone otcetera repo to web services dir
  git:
    repo: "{{ otcetera_git_remote }}"
    dest: "{{ ws_dir }}/otcetera"
    version: "{{ otcetera_ws_branch }}"

- name: install requests into {{venv_otcws}} for testing
  pip:
    virtualenv: "{{ venv_otcws }}"
    name: "requests"