---

- name: Clone otcetera repo to web services dir
  git:
    repo: "{{ otcetera_git_remote }}"
    dest: "{{ ws_dir }}/otcetera"
    version: "{{ otcetera_ws_branch }}"

- name: create the configure script for otcetera for webservices
  command: bash bootstrap.sh
  args:
    chdir: "{{ws_dir}}/otcetera"
    creates: "{{ws_dir}}/otcetera/configure"

- name: install requests into {{tolws_venv}} for testing
  pip:
    virtualenv: "{{ tolws_venv }}"
    name: "requests"