---
- name: Create parent of unpacked
  file:
    path: "{{ unpacked_dir }}"
    state: directory

- name: Unpack neo4j for taxomachine
  unarchive:
    src: "{{ downloads_dir }}/neo4j.tgz"
    dest: "{{ unpacked_dir }}"
    remote_src: yes
    creates: "{{ unpacked_dir }}/neo4j-community-1.9.5"

- name: "See taxomachine_neo4j_dir"
  stat:
    path: "{{ taxomachine_neo4j_dir }}"
  register: taxo_neo_dir

- name: Create scaffold for neo4j apps
  command: cp -r "{{ unpacked_dir }}/neo4j-community-1.9.5" "{{ taxomachine_neo4j_dir }}"
  when: (not taxo_neo_dir.stat.exists)

- name: Create parent of unpacked
  file:
    path: "{{ taxomachine_neo4j_dir }}/data/graph.db"
    state: directory

- name: "See taxomachine graph db is in the data dir"
  stat:
    path: "{{ taxomachine_neo4j_dir }}/data/graph.db/index.db"
  register: index_db

- name: Unpack a snapshot of the taxomachine db
  command: tar xfvz ~/downloads/taxomachine-20170414.db.tgz .
  args:
    chdir: "{{ taxomachine_neo4j_dir }}/data/graph.db"
  when: (not index_db.stat.exists)

- name: Create parent of unpacked
  file:
    path: "{{ users_bin_dir }}"
    state: directory

- name: Write neo4j launch script
  template:
    src: templates/restart_neo4j_sh.j2
    dest: "{{ users_bin_dir }}/restart_neo4j.sh"


- name: Write neo4j-server.properties
  template:
    src: templates/neo4j-server.properties.j2
    dest: "{{ taxomachine_neo4j_dir }}/conf/neo4j-server.properties"