---
# Install a nice, modern (in 2018) g++
- name: Add the PPA for software that is considered "testing" on Ubuntu 16.04 (as of May, 2018)
  apt_repository:
    repo: ppa:ubuntu-toolchain-r/test
  become: true
  become_method: sudo

- name: Install gcc-7 and g++-7 and autotools
  apt: name={{ item }} state=present
  with_items:
    - gcc-7
    - g++-7
    - autoconf
    - automake
  become: true
  become_method: sudo

- name: Make g++-7 and gcc-7 the defaults
  alternatives:
    name: "{{item}}"
    link: "/usr/bin/{{item}}"
    path: "/usr/bin/{{item}}-7"
  with_items:
    - gcc
    - g++
  become: true
  become_method: sudo
