---
- name: "update alternatives to Java 8"
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  become: true
  become_method: sudo

- name: "update alternatives for JDK"
  alternatives:
    name: javac
    path: /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
  become: true
  become_method: sudo
