---
# apache tasks
- name: Install apache using apt
  become: yes
  remote_user: deploy
  apt:
    name:
      - apache2
    state: present

- name: Install mod-wsgi using apt
  become: yes
  remote_user: deploy
  apt:
    name:
      - libapache2-mod-wsgi
    state: present

- name: enable apache2 modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - wsgi
    - proxy
    - proxy_http
    - rewrite
    - ssl
    - cgid
  become: true
  remote_user: deploy
  become_method: sudo

- name: write /etc/apache2/sites-available/opentree.conf
  template:
    src: templates/opentree_conf.j2
    dest: "/etc/apache2/sites-available/opentree.conf"
  become: true
  remote_user: deploy
  become_method: sudo
  notify:
    - restart apache2

- name: write /etc/apache2/sites-available/opentree-ssl.conf
  template:
    src: templates/opentree_ssl_conf.j2
    dest: "/etc/apache2/sites-available/opentree-ssl.conf"
  become: true
  remote_user: deploy
  become_method: sudo
  notify:
    - restart apache2


- name: write /etc/apache2/opentree-shared.conf
  template:
    src: "{{ 'templates/opentree_devapi_conf.j2' if 'phylesystemapi' in role_names else 'templates/opentree_shared_conf.j2' }}" 
    dest: "/etc/apache2/opentree-shared.conf"
  vars:
    phylesystem_api_stub: devphylesystemapi
    otindex_stub: devotindex
  become: true
  remote_user: deploy
  become_method: sudo
  notify:
    - restart apache2

- name: Display apache-config template used
  debug: msg="{{ 'templates/opentree_devapi_conf.j2' if 'phylesystemapi' in role_names else 'templates/opentree_shared_conf.j2' }}"

- name: enable the opentree site
  file:
    src: /etc/apache2/sites-available/opentree.conf
    dest: /etc/apache2/sites-enabled/000-opentree.conf
    state: link
  become: true
  remote_user: deploy
  become_method: sudo
  notify:
    - restart apache2

- name: enable the opentree ssl sites
  file:
    src: /etc/apache2/sites-available/opentree-ssl.conf
    dest: /etc/apache2/sites-enabled/001-opentree-ssl.conf
    state: link
  become: true
  remote_user: deploy
  become_method: sudo
  notify:
    - restart apache2

- name: disable the default apache site (remove symlink)
  file:
    dest: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  become: true
  remote_user: deploy
  become_method: sudo
  notify:
    - restart apache2
