# top-level playbook for nexttree (creating and serving a new
# synthetic tree)

# assumes deploy user with sudo access exists
---
- hosts: nexttree
  gather_facts: False

  pre_tasks:
    - name: Check Ansible version
      assert:
        that: '(ansible_version.major, ansible_version.minor, ansible_version.revision) >= (2, 5, 1)'
        msg: 'Please install the recommended version 2.5.1+. You have Ansible {{ ansible_version.string }}.'
      run_once: yes

    - name: Install basic libraries and tools using apt
      become: yes
      apt:
        name:
          - git-core
          - python3-pip
          - python3-venv
          - python-setuptools
          - python-virtualenv
          - unzip
        state: present

  tasks:

    - name: Ensure a locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present
      become: yes

    - name: Build synth tree
      include_role:
        name: synthesis
      when: build_synthesis

    - name: Get synthesis tree and OTT for web services
      include_role:
        name: ws_data

    - name: Install otcetera for serving the tree
      include_role:
        name: otcetera
      vars:
        install_location: "{{ ws_dir }}/cpp_apps"

    - name: Install ws_wrapper
      include_role:
        name: ws_wrapper
      vars:
        install_location: "{{ ws_dir }}/repos"

    - name: Install headless webapp
      include_role:
        name: webapp
      vars:
        install_location: "{{ ws_dir }}/repos"

    - name: Install and configure apache
      include_role:
        name: apache


  handlers:
    - name: restart apache2
      become: true
      service: name=apache2 state=restarted
  #   - name: restart otcetera webservices
  #     service:
