# top-level playbook for nexttree (creating and serving a new
# synthetic tree)
# assumes deploy user with sudo access exists
---
- hosts: all
  gather_facts: False

  pre_tasks:
    - name: Check Ansible version
      assert:
        that: '(ansible_version.major, ansible_version.minor, ansible_version.revision) >= (2, 5, 1)'
        msg: 'Please install the recommended version 2.5.1+. You have Ansible {{ ansible_version.string }}.'
      run_once: yes

    - name: Install basic libraries and tools using apt
      become: yes
      apt:
        name:
          - git-core
          - python3-pip
          - python3-venv
          - python-setuptools
        state: present

  roles:
    #- apache
    - peyotl
    - propinquity
    - role: otcetera
      vars:
        clone_location: "{{ synth_dir }}"
        otcws: False
        otcetera_branch: "{{ otcetera_synth_branch }}"
    #- otcetera # for serving the tree, uses vars from group_vars & role



  # handlers:
  #   - name: restart apache
  #     become: true
  #     service: name=apache2 state=restarted
