---
- hosts:
    - fullstack
  gather_facts: False
- hosts: dates
  gather_facts: False

  pre_tasks:
    - name: Check Ansible version
      assert:
        that: '(ansible_version.major, ansible_version.minor, ansible_version.revision) >= (2, 5, 1)'
        msg: 'Please install the recommended version 2.5.1+. You have Ansible {{ ansible_version.string }}.'
      run_once: yes

    - name: Install basic libraries and tools using apt
      become: yes
      apt:
        name:
          - git-core
          - python3-pip
          - python3-venv
          - python-setuptools
          - python-virtualenv
          - unzip
          - daemonize
        state: present

  tasks:

    - name: Ensure a locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present
      become: yes

    - name: load data for otcetera
      include_role:
        name: ws_data

    - name: Install and configure otcetera
      include_role:
        name: otcetera

    - name: Install ws_wrapper
      include_role:
        name: ws_wrapper
      vars:
        install_location: "{{ ws_dir }}/repos"

    - name: Install and configure apache
      include_role:
        name: apache



  handlers:
    - name: restart apache2
      become: true
      service: name=apache2 state=restarted
  #   - name: restart otcetera webservices
  #     service:
