---
- hosts: nexttree
  gather_facts: False

# start by installing required packages (note that postgresql packages
# installed separately in postgresql role and apache packages installed
# in apache role)

  pre_tasks:
    # python2 might not be installed on server (e.g. Ubuntu16)
    - name: Install basic python packages, build tools and git
      become: true
      become_method: sudo
      apt: name={{ item }} state=present
      with_items:
        - virtualenv
        - git-core
        - build-essential
        - python-dev
        - python-apt

#    - name: Install some system-wide python packages
#      pip:
#        name="{{ item }}"
#        with_items:
#          -

  roles:
    - { role: users}
    - { role: cplusplusdev}