---
# Adapted from roles/phylesystem-api (also in Pyramid)

- name: uninstall setuptools
  pip:
    name: setuptools
    state: absent
    virtualenv: "{{ venv_pyramid }}"

- name: Install downgraded setuptools for peyotl install
  pip:
    name: setuptools<58.0.0
    virtualenv: "{{ venv_pyramid }}"

## Install and configure peyotl
- name: Install peyotl ({{ peyotl_webapp_branch }})
  include_role:
    name: peyotl
  vars:
    install_location: "{{ repo_dir }}"
    configure_peyotl: True
    python_version: python3
    venv_peyotl: "{{ venv_pyramid }}"
    peyotl_branch: "{{ peyotl_webapp_branch }}"

- name: Clone tree-viewer repo
  git:
    repo: "{{ tree_viewer_git_remote }}"
    dest: "{{ install_dir }}/webapp-tree-viewer"
    version: "{{ tree_viewer_branch }}"

- name: Install waitress
  pip:
    name: waitress
    virtualenv: "{{ venv_pyramid }}"

- name: Install tree-viewer python requirements
  pip:
    # use the output of 'pip freeze' for safest results
    requirements: "{{ install_dir }}/webapp-tree-viewer/requirements.txt"
    virtualenv: "{{ venv_pyramid }}"
    ## NOTE Sometimes requirements.txt can pick up cruft that makes 
    ## our install fail. In that case, try the looser inputs in
    ## file  'requirements.in'

- name: Install tree viewer
  pip:
    name: "{{ install_location }}/webapp-tree-viewer/synthetic_tree_viewer"
    extra_args: '-e'
    virtualenv: "{{ venv_pyramid }}"

- name: Create dir for tree-viewer config file
  file:
    state: directory
    path: "{{ tree_viewer_config_location }}"

# TODO: create NON-curatorless config for dev / prod
- name: Create tree-viewer config file from template
  template:
    src: templates/treeview_app_config.j2
    dest: "{{ tree_viewer_config_location }}/config.ini"

- name: Create dir for curation-app config file
  file:
    state: directory
    path: "{{ curation_app_config_location }}"
  notify:
    - restart apache2
  when: install_curator

- name: Create curator-app config file from template
  template:
    src: templates/curator_app_config.j2
    dest: "{{ curation_app_config_location }}/config"
  notify:
    - restart apache2
  when: install_curator

- name: ensure log directory exists and is writable
  file:
      path: "{{ logfile_dir }}"
      state: directory

- name: ensure tree-viewer log file exists and is writable
  copy:
    content: ""
    dest: "{{ tree_viewer_logging_filepath }}"
    force: no

- name: create script directory if not found
  ansible.builtin.file:
    path: "{{ script_location }}/local/bin"
    state: directory
    mode: u=rwx,g=r,o=r

- name: write launch_tree_viewer.sh script
  template:
    src: templates/launch_tree_viewer_sh.j2
    dest: "{{ script_location }}/local/bin/launch_tree_viewer.sh"
    # we'll call this launcher as the final task

# More details specific to our web apps AS Github apps
#
# TODO Review all of this. Where should it go?

# first, the synthetic tree viewer
- name: Check for client secret
  stat:
    path: "{{ install_location }}/opentree/webapp/private/GITHUB_CLIENT_SECRET"
  register: github_client_secret

- name: copy client secret for github treeview app to web2py applications dir
  copy:
    src: "{{ tree_explorer_client_secret }}"
    dest: "{{ install_location }}/opentree/webapp/private/GITHUB_CLIENT_SECRET"
    mode: 400
  when: not github_client_secret.stat.exists

- name: Check for app key
  stat:
    path: "{{ install_location }}/opentree/webapp/private/GITHUB_APP_PRIVATE_KEY_PEM"
  register: github_app_priv_key_pem

- name: copy private key for github app to web2py applications dir
  copy:
    src: "{{ tree_explorer_pem_path }}"
    dest: "{{ install_location }}/opentree/webapp/private/GITHUB_APP_PRIVATE_KEY_PEM"
    mode: 400
  when: not github_app_priv_key_pem.stat.exists

# then (perhaps) the study-curation app
- name: Check for curator secret
  stat:
    path: "{{ install_location }}/opentree/curator/private/GITHUB_CLIENT_SECRET"
  register: github_curator_secret
  when: install_curator

- name: copy client secret for github curator app to web2py applications dir
  copy:
    src: "{{ curator_client_secret }}"
    dest: "{{ install_location }}/opentree/curator/private/GITHUB_CLIENT_SECRET"
    mode: 400
  when: (install_curator) and (not github_curator_secret.stat.exists)

- name: Check for curator app key
  stat:
    path: "{{ install_location }}/opentree/curator/private/GITHUB_APP_PRIVATE_KEY_PEM"
  register: github_curator_app_priv_key_pem
  when: install_curator

- name: copy private key for github app to web2py applications dir
  copy:
    src: "{{ curator_pem_path }}"
    dest: "{{ install_location }}/opentree/curator/private/GITHUB_APP_PRIVATE_KEY_PEM"
    mode: 400
  when: (install_curator) and (not github_curator_app_priv_key_pem.stat.exists)

#- name: copy opentree api token from local machine
#  ansible.builtin.copy:
#    src: ~/.ssh/opentree/OPENTREEAPI_OAUTH_TOKEN
#    dest: /home/{{ opentree_user }}/.ssh/OPENTREEAPI_OAUTH_TOKEN
#    mode: '0600'


- name: "launch tree viewer via launch script"
  command: "bash {{ script_location }}/local/bin/launch_tree_viewer.sh || exit"

