---
- name: "Create python 2.7 virtualenv if it does not already exist"
  command:
    cmd: virtualenv -p python2.7 "{{ venv_web2py }}"
    creates: "{{ venv_web2py }}"

- name: Clone opentree repo
  git:
    repo: "{{ opentree_git_remote }}"
    dest: "{{ install_location }}/opentree"
    version: "{{ opentree_branch }}"
    force: yes


- name: install opentree prerequisites into {{venv_web2py}}
  pip:
    virtualenv: "{{ venv_web2py }}"
    virtualenv_python: "{{ web2py_python_version }}"
    requirements: "{{ install_location }}/opentree/requirements.txt"

- name: create link to opentree webapp in web2py applications dir
  file:
    src: "{{ install_location }}/opentree/webapp"
    dest: "{{ install_location }}/web2py/applications/opentree"
    state: link

- name: Check for client secret
  stat:
    path: "{{ install_location }}/opentree/webapp/private/GITHUB_CLIENT_SECRET"
  register: github_client_secret

- name: copy client secret for github treeview app to web2py applications dir
  copy:
    src: "{{ tree_explorer_client_secret }}"
    dest: "{{ install_location }}/opentree/webapp/private/GITHUB_CLIENT_SECRET"
    mode: 400
  when: not github_client_secret.stat.exists

- name: Check for app key
  stat:
    path: "{{ install_location }}/opentree/webapp/private/GITHUB_APP_PRIVATE_KEY_PEM"
  register: github_app_priv_key_pem

- name: copy private key for github app to web2py applications dir
  copy:
    src: "{{ tree_explorer_pem_path }}"
    dest: "{{ install_location }}/opentree/webapp/private/GITHUB_APP_PRIVATE_KEY_PEM"
    mode: 400
  when: not github_app_priv_key_pem.stat.exists

- name: create link to curator app in web2py applications dir
  file:
    src: "{{ install_location }}/opentree/curator"
    dest: "{{ install_location }}/web2py/applications/curator"
    state: link
  when: install_curator


- name: Check for curator secret
  stat:
    path: "{{ install_location }}/opentree/curator/private/GITHUB_CLIENT_SECRET"
  register: github_curator_secret

- name: copy client secret for github curator app to web2py applications dir
  copy:
    src: "{{ curator_client_secret }}"
    dest: "{{ install_location }}/opentree/curator/private/GITHUB_CLIENT_SECRET"
    mode: 400
  when: (install_curator) and (not github_curator_secret.stat.exists)

- name: Check for curator app key
  stat:
    path: "{{ install_location }}/opentree/curator/private/GITHUB_APP_PRIVATE_KEY_PEM"
  register: github_curator_app_priv_key_pem

- name: copy private key for github app to web2py applications dir
  copy:
    src: "{{ curator_pem_path }}"
    dest: "{{ install_location }}/opentree/curator/private/GITHUB_APP_PRIVATE_KEY_PEM"
    mode: 400
  when: (install_curator) and (not github_curator_app_priv_key_pem.stat.exists)

# TODO: create non curatorless config for dev / prod
- name: configure opentree webapp
  template:
    src: templates/treeview_app_config.j2
    dest: "{{ install_location }}/opentree/webapp/private/config"

- name: configure curator webapp
  template:
    src: templates/curator_app_config.j2
    dest: "{{ install_location }}/opentree/curator/private/config"
  notify:
    - restart apache2
  when: install_curator

- name: configure opentree webapp
  template:
    src: templates/routes_py.j2
    dest: "{{ install_location }}/web2py/routes.py"
  notify:
    - restart apache2

#- name: copy opentree api token from local machine
#  ansible.builtin.copy:
#    src: ~/.ssh/opentree/OPENTREEAPI_OAUTH_TOKEN
#    dest: /home/{{ opentree_user }}/.ssh/OPENTREEAPI_OAUTH_TOKEN
#    mode: '0600'
