---
phylesystem_1_branch: master
collections_1_branch: before-summer
phylesystem_grandpar_git_remote: https://github.com/OpenTreeOfLife/phylesystem
phylesystem_1_git_remote: https://github.com/OpenTreeOfLife/phylesystem-1
collections_1_git_remote: https://github.com/OpenTreeOfLife/collections-1
ott_download_url: http://files.opentreeoflife.org/ott/ott3.0/ott3.0draft6.tgz
ansible_user: opentree