---

# Install and configure peyotl library
# Not pip installable, so install from locally cloned repo
# Assumes git, python3, pip, virtualenv already installed

- name: Create the synthesis directory
  file:
    state: directory
    path: "{{ synth_dir }}"

- name: Clone peyotl repo
  git:
    repo: "{{ peyotl_git_remote }}"
    dest: "{{ synth_dir }}/peyotl"
    version: "{{ peyotl_synth_branch }}"

- name: Create dir for peyotl config file
  file:
    state: directory
    path: "{{ peyotl_config_location }}"

- name: Create peyotl config file from template
  template:
    src: templates/config.j2
    dest: "{{ peyotl_config_location }}/config.ini"

- name: "Create python 3 virtualenv if it does not already exist"
  command:
    cmd: python3 -m venv "{{ venv_synth }}"
    creates: /home/{{ ansibleuser }}/venv_synth

- name: Install peyotl prerequisites into {{venv_synth}}
  pip:
    requirements: "{{ synth_dir }}/peyotl/requirements.txt"
    virtualenv: "{{ venv_synth }}"

- name: Install peyotl into {{venv_synth}} as a link
  pip:
    name: "{{ synth_dir }}/peyotl"
    extra_args: '-e'
    virtualenv: "{{ venv_synth }}"

- name: Install Chameleon into {{venv_synth}}
  pip:
    name: Chameleon
    virtualenv: "{{ venv_synth }}"
