---

# Install and configure peyotl library
# Not pip installable, so install from locally cloned repo
# Assumes git, python3, pip, virtualenv already installed

- name: Clone peyotl repo
  git:
    repo: "{{ peyotl_git_remote }}"
    dest: "{{ install_location }}/peyotl"
    version: "{{ peyotl_branch }}"

- name: Create dir for peyotl config file
  file:
    state: directory
    path: "{{ peyotl_config_location }}"
  when: configure_peyotl

- name: Create peyotl config file from template
  template:
    src: templates/config.j2
    dest: "{{ peyotl_config_location }}/config"
  when: configure_peyotl

- name: "Create python 3 virtualenv if it does not already exist"
  command:
    cmd: virtualenv -p python3 "{{ venv_peyotl }}"
    creates: "{{ venv_peyotl }}"

- name: Clone peyutil repo for propinquity
  git:
    repo: "https://github.com/OpenTreeOfLife/peyutil"
    dest: "{{ install_location }}/peyutil4propinquity"
    version: "main"

- name: Install peyutil prerequisites into "{{venv_peyotl}}"
  pip:
    requirements: "{{ install_location }}/peyutil4propinquity/requirements.txt"
    virtualenv: "{{ venv_peyotl }}"
    virtualenv_python: "{{ python_version }}"

- name: Install peyutil into {{venv_peyotl}} as a link
  pip:
    name: "{{ install_location }}/peyutil4propinquity"
    extra_args: '-e'
    virtualenv: "{{ venv_peyotl }}"
    virtualenv_python: "{{ python_version }}"

- name: Clone nexson repo for propinquity
  git:
    repo: "https://github.com/OpenTreeOfLife/nexson"
    dest: "{{ install_location }}/nexson4propinquity"
    version: "main"

- name: Install nexson prerequisites into "{{venv_peyotl}}"
  pip:
    requirements: "{{ install_location }}/nexson4propinquity/requirements.txt"
    virtualenv: "{{ venv_peyotl }}"
    virtualenv_python: "{{ python_version }}"

- name: Install nexson into {{venv_peyotl}} as a link
  pip:
    name: "{{ install_location }}/nexson4propinquity"
    extra_args: '-e'
    virtualenv: "{{ venv_peyotl }}"
    virtualenv_python: "{{ python_version }}"

- name: Install peyotl prerequisites into "{{venv_peyotl}}"
  pip:
    requirements: "{{ install_location }}/peyotl/requirements.txt"
    virtualenv: "{{ venv_peyotl }}"
    virtualenv_python: "{{ python_version }}"

- name: Install peyotl into {{venv_peyotl}} as a link
  pip:
    name: "{{ install_location }}/peyotl"
    extra_args: '-e'
    virtualenv: "{{ venv_peyotl }}"
    virtualenv_python: "{{ python_version }}"

- name: Install Chameleon into {{venv_peyotl}}
  pip:
    name: Chameleon
    virtualenv: "{{ venv_peyotl }}"
    virtualenv_python: "{{ python_version }}"
