---

- name: Pull otcetera repo
  git:
    repo: "{{ otcetera_git_remote }}"
    dest: "{{ ws_dir }}/otcetera"
    version: "{{ otcetera_ws_branch }}"

- name: write reconf.sh script
  template:
    src: templates/reconf_ws_sh.j2
    dest: "{{ ws_dir }}/buildotc/reconf.sh"

- name: Create the Makefiles by running our invocation of configure (via reconf.sh)
  command: bash reconf.sh
  args:
    chdir: "{{ ws_dir }}/buildotc"
    creates: "{{ ws_dir }}/buildotc/Makefile"
