---

- name: Pull otcetera repo
  git:
    repo: "{{ otcetera_git_remote }}"
    dest: "{{ ws_dir }}/otcetera"
    version: "{{ otcetera_ws_branch }}"

- name: create the configure script for otcetera for webservices
  command: bash bootstrap.sh
  args:
    chdir: "{{ws_dir}}/otcetera"
    creates: "{{ws_dir}}/otcetera/configure"

- name: write reconf.sh script
  template:
    src: templates/reconf_ws_sh.j2
    dest: "{{ ws_dir }}/buildotc/reconf.sh"
  register: result

- name: Check if the otcetera Makefile exists
  stat:
    path: "{{ ws_dir }}/buildotc/Makefile"
  register: otcmakefile

- name: Create the Makefiles by running our invocation of configure (via reconf.sh)
  command: bash reconf.sh
  args:
    chdir: "{{ ws_dir }}/buildotc"
  when: result.changed or not otcmakefile.stat.exists