---

- name: Runs ninja to build and install otc
  command: ninja -C build install
  args:
    chdir: "{{synth_dir}}/buildotc"


- name: Performs the otc tests
  command: ninja -C build test
  args:
    chdir: "{{synth_dir}}/buildotc"
