---

- name: Runs "make" on the otcetera-cli dir
  make:
    chdir: "{{ ws_dir }}/buildotc"
    target: all
    params:
      NUM_THREADS: 6

- name: Runs tests on the new otcetera build
  command: "bash -c 'source {{ tolws_venv }}/bin/activate && make check'"
  args:
    chdir: "{{ ws_dir }}/buildotc"

- name: Install the new otcetera build
  make:
    chdir: "{{ ws_dir }}/buildotc"
    target: install
