---
- name: Pull ws_wrapper repo
  git:
    repo: "{{ ws_wrapper_git_remote }}"
    dest: "{{ install_location }}/ws_wrapper"
    version: "{{ ws_wrapper_branch }}"

# Simple clone + install rather than using full peyotl role because no
# configuration required
- name: Clone peyotl repo
  git:
    repo: "{{ peyotl_git_remote }}"
    dest: "{{ install_location }}/peyotl"
    version: "{{ peyotl_otc_ws_branch }}"

- name: "install ws_wrapper and peyotl in {{ venv_otcws }}"
  pip:
    name:
      - "{{ install_location }}/ws_wrapper"
      - "{{ install_location }}/peyotl"
    extra_args: '-e'   # link rather than copy
    virtualenv: "{{ venv_otcws }}"

- name: Create config file from template
  template:
    src: templates/config.j2
    dest: "{{ install_location }}/ws_wrapper/wswrapper.ini"

# Last two tasks launch ws_wrapper application

- name: cpp apps dir exists and is writable
  file:
      path: "{{ script_location }}/local/bin"
      state: directory


- name: write launch_ws_wrapper.sh script
  template:
    src: templates/launch_ws_wrapper_sh.j2
    dest: "{{ script_location }}/local/bin/launch_ws_wrapper.sh"

- name: "launch ws_wrapper server via launch script"
  command: "bash {{ script_location }}/local/bin/launch_ws_wrapper.sh"
