---

- name: Clone restbed repo to web services dir
  git:
    repo: "{{ restbed_git_remote }}"
    dest: "{{ ws_dir }}/restbed"
    version: "{{ restbed_git_tag }}"

- name: Create restbed build dir
  file:
    state: directory
    path: "{{ ws_dir }}/restbed/build"
    owner: "{{ normaluser }}"
    group: "{{ normaluser }}"

- name: create restbuild Makefile
  command: "cmake -DBUILD_SSL=NO -DCMAKE_INSTALL_PREFIX={{ ws_dir }}/installed .."
  args:
    chdir: "{{ ws_dir }}/restbed/build"
    creates: "{{ ws_dir }}/restbed/build/Makefile"

- name: build and install resetbed
  make:
    chdir: "{{ ws_dir }}/restbed/build"
    target: install
