---

- name: Clone restbed repo to web services dir
  git:
    repo: "{{ restbed_git_remote }}"
    dest: "{{ ws_dir }}/restbed"
    version: "{{ restbed_git_tag }}"

- name: Create restbed build dir
  file:
    state: directory
    path: "{{ ws_dir }}/restbed/build"
    owner: "{{ normaluser }}"
    group: "{{ normaluser }}"

- name: create restbuild Makefile
  command: "cmake .. -G Ninja -DBUILD_SSL=NO -DCMAKE_INSTALL_PREFIX={{ ws_dir }}/local"
  args:
    chdir: "{{ ws_dir }}/restbed/build"
    creates: "{{ ws_dir }}/restbed/build/build.ninja"

- name: build and install restbed
  command: ninja install
  args:
    chdir: "{{ ws_dir }}/restbed/build"
    creates: "{{ ws_dir }}/local/library/librestbed.a"

