---
# NOTE that we'll default to save (dev) values here to avoid disasters on
# production. For staging, production, or other situations, override at the
# host level by creating '{host}.yml` (for example `phylesystemapi.yml`,
# `production.yml`, ...)

# deployed branch for each subsystem/repo
phylesystem_api_branch: celery-replacement
peyotl_phylesystemapi_branch: master

install_dir: "/home/{{ansibleuser}}/repos"
# NB - variables in ALL_CAPS_FORM are used on only within this file!
SHARED_DOCSTORE_PARENT: "{{ install_dir }}/docstore/"

canonical_host: devapi.opentreeoflife.org
logfile_dir: "/home/{{ ansibleuser }}/logs"
phylesystem_api_logging_filepath: "{{ logfile_dir }}/phylesystem_api_main.log"
phylesystem_api_config_location: "/home/{{ansibleuser}}/configs/phylesystem_api"
phylesystem_parent: "{{ SHARED_DOCSTORE_PARENT }}"
  # TODO remove this in favor of phylesystem_repo_parent below?
venv_phylesystem_api: "/home/{{ ansibleuser }}/venv_phylesystem_api"
script_location: "{{ ws_dir }}"

# configuration for the phylesystem-api Pyramid app
# NB that to avoid disaster, we default to safe values and a dev environment!
read_only_mode: true

# the full path to where a local phylesystem.git can be found
phylesystem_repo_parent: "{{ SHARED_DOCSTORE_PARENT }}"
phylesystem_repo_path: "{{ SHARED_DOCSTORE_PARENT }}phylesystem-0"
# prefix for new study ids. should be of the form [a-z][a-z]_
# new_study_prefix = zz_

# local paths for minor repos
collections_repo_parent: "{{ SHARED_DOCSTORE_PARENT }}"
collections_repo_path: "{{ SHARED_DOCSTORE_PARENT }}collections-0"
amendments_repo_parent: "{{ SHARED_DOCSTORE_PARENT }}"
amendments_repo_path: "{{ SHARED_DOCSTORE_PARENT }}amendments-0"

# the remote to push changes to
# This will usually be "origin" on a local dev machine where phylesystem.git
# was cloned via SSH (git@github.com:...)
# On deployed servers, which use anonymous git:// protocol, we add a new
# remote "originssh" which can be pushed to
phylesystem_repo_remote: originssh

# remotes for minor repos
collections_repo_remote: originssh 
amendments_repo_remote: originssh

# these allow us to specify the SSH keys that git pushes
# will use. Leave the config keys in this config file,
# without any values assigned, to not use this feature
## Need to generate key on server, 
## and set in GitHub as deploy key for appropriate app.
git_ssh: "{{ install_dir }}/phylesystem-api/bin/git.sh"
git_private_key: "/home/{{ ansibleuser }}/.ssh/id_ed25519_shared"

# other API endpoints
DEFAULT_API_BASE_URL: "https://devapi.opentreeoflife.org"
oti_base_url: "{{ DEFAULT_API_BASE_URL }}"
collections_api_base_url: "https://{{ canonical_host }}/"
amendments_api_base_url: "https://{{ canonical_host }}/"
favorites_api_base_url: "https://{{ canonical_host }}/"
otindex_base_url: "https://devotindex.opentreeoflife.org"

# Github repo org+name for each docstore repo
#
STUDIES_GITHUB_NAME: OpenTreeOfLife/phylesystem-0
COLLECTIONS_GITHUB_NAME: OpenTreeOfLife/collections-0
AMENDMENTS_GITHUB_NAME: OpenTreeOfLife/amendments-0

# URLs for each docstore repo
opentree_docstore_url: https://github.com/{{ STUDIES_GITHUB_NAME }}
collections_repo_url: https://github.com/{{ COLLECTIONS_GITHUB_NAME }}
amendments_repo_url: https://github.com/{{ AMENDMENTS_GITHUB_NAME }}

# git-config 'remote.url' for each docstore repo
opentree_docstore_remote_url: git@github.com:{{ STUDIES_GITHUB_NAME }}.git
collections_repo_remote_url: git@github.com:{{ COLLECTIONS_GITHUB_NAME }}.git
amendments_repo_remote_url: git@github.com:{{ AMENDMENTS_GITHUB_NAME }}.git

# we'll loop over docstore repos in tasks/main
repo_paths:
  - { github_url: "{{ opentree_docstore_url }}",
      local_path: "{{ phylesystem_repo_path }}",
      remote_url: "{{ opentree_docstore_remote_url }}" }
  - { github_url: "{{ collections_repo_url }}",
      local_path: "{{ collections_repo_path }}",
      remote_url: "{{ collections_repo_remote_url }}" }
  - { github_url: "{{ amendments_repo_url }}",
      local_path: "{{ amendments_repo_path }}",
      remote_url: "{{ amendments_repo_remote_url }}" }

# API logging levels
open_tree_api_logging_level: info
open_tree_api_logging_formatter: rich
open_tree_api_logging_filepath: "/home/{{ ansibleuser }}/logs/api.log"
