---
- name: write ~/.opentree config file used by propinquity
  template:
    src: templates/dot_opentree.j2
    dest: "/home/{{ ansible_user }}/.synth_flag_opentree"

- name: write ~/.opentree config file used by propinquity
  template:
    src: templates/synth_peyotl_conf_ini.j2
    dest: "{{ synth_dir }}/propinquity/synth_peyotl_conf_{{ next_synth_version }}.ini"

- name: copy propinquity config.opentree.synth to next.config
  copy:
    src: "{{ synth_dir }}/propinquity/config.opentree.synth"
    dest: "{{ synth_dir }}/propinquity/next.config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: yes

- name: replace version number
  replace:
    path: "{{ synth_dir }}/propinquity/next.config"
    regexp: '^synth_id+ =+ opentree[-0-9.]+ *$'
    replace: "synth_id = opentree{{ next_synth_version }}"

- name: "See if a completed build dir for {{ next_synth_version }} exists"
  stat:
    path: '{{ synth_dir }}/tree_builds/opentree{{ next_synth_version }}'
  register: tb_dir

- name: "See if an inprogress build dir for {{ next_synth_version }} exists"
  stat:
    path: '{{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}'
  register: iptb_dir
  when: not tb_dir.stat.exists

- name: "Create an empty directory (locally)"
  local_action:
    module: file
    state: directory
    path: "/tmp/empty_dir_for_ansible_hack"

- name: "empty {{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}"
  synchronize:
    src: /tmp/empty_dir_for_ansible_hack
    dest: "{{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}"
    delete: yes
    recursive: yes
  when: (not tb_dir.stat.exists) and iptb_dir.stat.exists and iptb_dir.stat.isdir

- name: "delete {{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}"
  file:
    path: "{{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}"
    state: absent
  when: (not tb_dir.stat.exists) and iptb_dir.stat.exists and iptb_dir.stat.isdir

- name: "write invoke_opentree{{ next_synth_version }}."
  template:
    src: templates/invoke_sh.j2
    dest: "{{ synth_dir }}/propinquity/invoke_opentree{{ next_synth_version }}.sh"
  when: not tb_dir.stat.exists

- name: "build the synthetic tree at {{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}"
  command: "bash invoke_opentree{{ next_synth_version }}.sh"
  args:
    chdir: "{{synth_dir}}/propinquity"
    creates: "{{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}"
  when: not tb_dir.stat.exists

- name: "See if synthesis html docs were completed"
  stat:
    path: "{{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}/logs/index.html"
  register: log_index_html
  when: not tb_dir.stat.exists

- name: Moves synth tree from in_progress_tree_builds dir to tree_builds dir
  command: "mv '{{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}' '{{ synth_dir }}/tree_builds/opentree{{ next_synth_version }}'"
  args:
    creates: "{{ synth_dir }}/tree_builds/opentree{{ next_synth_version }}"
  when: log_index_html.stat.exists and not tb_dir.stat.exists


- name: Notify if build is old
  debug:
    msg: "The tree {{ synth_dir }}/tree_builds/opentree{{ next_synth_version }} already existed, so it was not rebuilt."
  when: tb_dir.stat.exists

- name: Notify if build failed
  debug:
    msg: "synthetic tree html generation failed. Check {{ synth_dir }}/in_progress_tree_builds/opentree{{ next_synth_version }}/logs/log-of-html-err.txt "
  when: (not tb_dir.stat.exists) and (not log_index_html.stat.exists)

