---
# We assume this is only called from the otcetera role,
# so the (shared) requirements are installed there, not here

- name: Create restbed dir
  file:
    path: "{{ install_location }}/restbed"
    state: directory

- name: Clone restbed repo
  git:
    repo: "{{ restbed_git_remote }}"
    dest: "{{ install_location }}/restbed/source"
    version: "{{ restbed_git_tag }}"
    recursive: yes  # yes is the default, but being explicit

- name: Create restbed build dir
  file:
    state: directory
    path: "{{ install_location }}/restbed/build"
    owner: "{{ ansibleuser }}"
    group: "{{ ansibleuser }}"

- name: create restbuild Makefile
  command: "cmake {{ install_location }}/restbed/source -G Ninja -DBUILD_SSL=NO -DBUILD_TESTS=NO -DCMAKE_INSTALL_PREFIX={{ ws_dir }}/local -DCMAKE_POSITION_INDEPENDENT_CODE=ON"
  args:
    chdir: "{{ install_location }}/restbed/build"
    creates: "{{ install_location }}/restbed/build/build.ninja"

- name: build and install restbed
  command: nice -n10 ninja install
  args:
    chdir: "{{ install_location }}/restbed/build"
    creates: "{{ ws_dir }}/local/library/librestbed.a"
