---

- name: Clone jade repo
  git:
    repo: "https://github.com/FePhyFoFum/jade"
    dest: "{{ repo_dir }}/jade"
    version: "master"
  notify:
    - install jade

- name: Clone ot-base repo
  git:
    repo: "https://github.com/OpenTreeOfLife/ot-base"
    dest: "{{ repo_dir }}/ot-base"
    version: "master"
  notify:
    - install ot-base

- name: Clone taxomachine repo
  git:
    repo: "{{ taxomachine_git_remote }}"
    dest: "{{ repo_dir }}/taxomachine"
    version: "{{ taxomachine_branch }}"
  notify:
    - "build taxomachine plugin"

- name: copy taxomachine jar
  copy:
    src: "{{ repo_dir }}/taxomachine/target/taxomachine-neo4j-plugins-0.0.1-SNAPSHOT.jar"
    dest: "{{ taxomachine_neo4j_dir }}/plugins/taxomachine-neo4j-plugins-0.0.1-SNAPSHOT.jar"
    remote_src: yes
