---
- name: Create a non-privileged user (e.g. the "opentree" user)
  user:
    name: "{{normaluser}}"

- name: Create non-privileged user's .ssh dir
  file:
    state: directory
    mode: 0700
    path: "/home/{{normaluser}}/.ssh"

- name: Move the authorized key over from the admin account
  copy:
    src: '/home/{{adminuser}}/.ssh/authorized_keys'
    dest: '/home/{{normaluser}}/.ssh/authorized_keys'
    owner: "{{normaluser}}"
    group: "{{normaluser}}"
    mode: 0644
    remote_src: yes