---

- name: Runs ninja to build and install otc
  command: ninja -C build
  args:
    chdir: "{{ws_dir}}/buildotc"


- name: write run_test.sh script
  template:
    src: templates/run_test_sh.j2
    dest: "{{ ws_dir }}/buildotc/run_test.sh"

- name: Performs the otc tests using the run_test.sh that sources the correct env
  command: bash run_test.sh
  args:
    chdir: "{{ws_dir}}/buildotc"

- name: Runs ninja to install otc
  command: ninja -C build install
  args:
    chdir: "{{ws_dir}}/buildotc"

