---
# Installs otindex and initializes database

- name: Clone chronosynth repo
  git:
    repo: https://github.com/OpenTreeOfLife/chronosynth.git
    dest: "{{ install_dir }}/chronosynth"
    version: "{{ chronosynth_branch }}"

- name: Install chronosynth python requirements
  pip:
    requirements: "{{ install_dir }}/chronosynth/requirements.txt"
    virtualenv: "{{ venv_otcws }}"

- name: install the package, force upgrade
  pip: 
    name: setuptools
    version: <58
    virtualenv: "{{ venv_otcws }}"


- name: Install chronosynth
  command: $VENV/bin/python setup.py develop
  environment:
    VENV: "{{ venv_otcws }}"
  args:
    chdir: "{{ install_dir }}/chronosynth"


- name: Create dir for chronosynth config file
  file:
    state: directory
    path: "{{ chronosynth_config_location }}"

- name: Create chronosynth config file from template
  template:
    src: templates/config.j2
    dest: "{{ chronosynth_config_location }}/config.ini"

- name: ensure log directory exists and is writable
  file:
      path: "{{ logfile_dir }}"
      state: directory

- name: ensure chronosynth log file exists and is writable
  copy:
    content: ""
    dest: "{{ chronosynth_logging_filepath }}"
    force: no
