---
# Installs otindex and initializes database

- name: Clone chronosynth repo
  git:
    repo: https://github.com/OpenTreeOfLife/chronosynth.git
    dest: "{{ install_dir }}/chronosynth"
    version: "{{ chronosynth_branch }}"
  become: yes
  become_user: opentree

- name: Install chronosynth python requirements
  pip:
    requirements: "{{ install_dir }}/chronosynth/requirements.txt"
    virtualenv: "{{ install_dir }}/../venv"
  become: yes 
  become_user: opentree

- name: install the package, force upgrade
  pip: 
    name: setuptools
    extra_args: --upgrade
    virtualenv: "{{ install_dir }}/../venv"
  become: yes 
  become_user: opentree


- name: Install chronosynth
  command: $VENV/bin/python setup.py develop
  environment:
    VENV: "{{ install_dir }}/../venv"
  args:
    chdir: "{{ install_dir }}/chronosynth"
  notify:
    - restart apache
  become: yes 
  become_user: opentree

# create pyramid config file
- name: Create config file from template
  template:
    src: templates/config.j2
    dest: "{{ install_dir }}/otindex/{{ config_filename }}"
  become: yes

- name: ensure chronosynth log file exists and is writable
  copy:
    content: ""
    dest: "{{ chronosynth_logging_filepath }}"
    force: no
    group: opentree
    owner: opentree
  become: true
