---

- name: Copy synth tree to served location.
  copy:
    src: "{{ synth_dir }}/tree_builds/opentree{{ next_synth_version }}"
    dest: "{{ otc_ws_data }}/synth_trees/"
    remote_src: true
    mode: preserve

- name: Copy OTT to served location.
  copy:
    src: "{{ synth_dir }}/tree_builds/ott-used-in-synth"
    dest: "{{ otc_ws_data }}/"
    remote_src: true
    mode: preserve

