---
peyotl_git_remote: https://github.com/OpenTreeOfLife/peyotl"
peyotl_config_location: "/home/{{ ansibleuser }}/.peyotl"
peyotl_synth_branch: master
venv_synth: /home/{{ ansibleuser }}/venv_synth

# template vars (used to create peyotl config)
phylesystem_parent: "{{ synth_dir }}"
repo_nexml2json: 1.2.1
ott_dir: "{{ synth_dir }}/ott"
logging_level: debug
peyotl_logging_filepath: "{{ synth_dir }}/peyotl.log"
logging_formatter: rich
