---
# Defaults set for building synth tree; for other installs, probably
# want different values of venv, install_location, configuration

peyotl_git_remote: https://github.com/OpenTreeOfLife/peyotl
peyotl_branch: master
venv_peyotl: /home/{{ ansibleuser }}/venv_peyotl
peyotl_install_location: "{{ repo_dir }}"
#venv_synth: /home/{{ ansibleuser }}/venv_synth

# don't need to do all of the configuration for many use cases
configure_peyotl: True
peyotl_config_location: "/home/{{ ansibleuser }}/.peyotl"

# template vars (used to create peyotl config)
phylesystem_parent: "{{ synth_dir }}"
repo_nexml2json: 1.2.1
ott_dir: "{{ synth_dir }}/ott"
logging_level: debug
peyotl_logging_filepath: "{{ logfile_dir }}/peyotl.log"
logging_formatter: rich
synth_dir: "/home/{{ ansibleuser }}/synth"
