---
- name: Install peyotl
  include_role:
    name: peyotl
  vars: 
    install_location: "{{ repo_dir }}"
    python_version: python3
    venv_peyotl: "{{ venv_phylesystem_api }}"


- name: Clone phylesystem-api repo
  git:
    repo: https://github.com/OpenTreeOfLife/phylesystem-api.git
    dest: "{{ install_dir }}/phylesystem-api"
    version: "{{ phylesystem_api_branch }}"

- name: Install waitress
  pip:
    name: waitress
    virtualenv: "{{ venv_phylesystem_api }}"


- name: Install phylesystem-api python requirements
  pip:
    requirements: "{{ install_dir }}/phylesystem-api/requirements.in"
    virtualenv: "{{ venv_phylesystem_api }}"


- name: Create dir for phylesystem-api config file
  file:
    state: directory
    path: "{{ phylesystem_api_config_location }}"


- name: Create phylesystem-api config file from template
  template:
    src: templates/config.j2
    dest: "{{ phylesystem_api_config_location }}/config.ini"

- name: ensure log directory exists and is writable
  file:
      path: "{{ logfile_dir }}"
      state: directory

- name: ensure phylesystem-api log file exists and is writable
  copy:
    content: ""
    dest: "{{ phylesystem_api_logging_filepath }}"
    force: no


- name: write launch_phylesystem_api.sh script
  template:
    src: templates/launch_phylesystem_api_sh.j2
    dest: "{{ script_location }}/local/bin/launch_phylesystem_api.sh"

- name: "launch ws_wrapper server via launch script"
  command: "bash {{ script_location }}/local/bin/launch_phylesystem_api.sh || exit"

