---
- name: Install peyotl ({{ peyotl_phylesystemapi_branch }})
  include_role:
    name: peyotl
  vars: 
    install_location: "{{ repo_dir }}"
    python_version: python3
    venv_peyotl: "{{ venv_phylesystem_api }}"
    peyotl_branch: "{{ peyotl_phylesystemapi_branch }}"

- name: Clone phylesystem-api repo
  git:
    repo: https://github.com/OpenTreeOfLife/phylesystem-api.git
    dest: "{{ install_dir }}/phylesystem-api"
    version: "{{ phylesystem_api_branch }}"

- name: Install waitress
  pip:
    name: waitress
    virtualenv: "{{ venv_phylesystem_api }}"


- name: Install phylesystem-api python requirements
  pip:
    requirements: "{{ install_dir }}/phylesystem-api/requirements.txt"
    virtualenv: "{{ venv_phylesystem_api }}"

- name: Install phylesystem-api
  pip:
    name: "{{ install_location }}/phylesystem-api/phylesystem_api"
    extra_args: '-e'
    virtualenv: "{{ venv_phylesystem_api }}"

- name: Create dir for phylesystem-api config file
  file:
    state: directory
    path: "{{ phylesystem_api_config_location }}"


## Get phylesystem data (studies and minor doc-types)
# NB - We clone each repo twice, once into a designated "docstore parent"
# directory and again into its mirror/ subdirectory.

- name: ensure shared docstore-parent dir exists, and ./mirror
  file:
      path: "{{ SHARED_DOCSTORE_PARENT }}"
      state: directory
  file:
      path: "{{ SHARED_DOCSTORE_PARENT }}mirror/"
      state: directory

- name: Clone/update studies repo
  loop:
    - "{{ phylesystem_repo_path }}"
    - "{{ phylesystem_repo_parent }}mirror"
  command: echo "...cloning/updating into '{{ item }}'..."
  git:
    repo: "{{ opentree_docstore_url }}"
    accept_newhostkey: yes      # good for occasionally changing host key
    ssh_opts: "-o StrictHostKeyChecking=accept-new"
    remote: "origin"            # default is 'origin'
    dest: "{{ item }}"
    recursive: yes              # yes is default; being explicit because submodules
    force: yes                  # clobber any locally modified patch files

- name: Clone/update collections repo
  loop:
    - "{{ collections_repo_path }}"
    - "{{ collections_repo_parent }}mirror"
  command: echo "...cloning/updating into '{{ item }}'..."
  git:
    repo: "{{ collections_repo_url }}"
    accept_newhostkey: yes      # good for occasionally changing host key
    ssh_opts: "-o StrictHostKeyChecking=accept-new"
    remote: "origin"            # default is 'origin'
    dest: "{{ item }}"
    recursive: yes              # yes is default; being explicit because submodules
    force: yes                  # clobber any locally modified patch files

- name: Clone amendments repo
  loop:
    - "{{ amendments_repo_path }}"
    - "{{ amendments_repo_parent }}mirror"
  command: echo "...cloning/updating into '{{ item }}'..."
  git:
    repo: "{{ amendments_repo_url }}"
    accept_newhostkey: yes      # good for occasionally changing host key
    ssh_opts: "-o StrictHostKeyChecking=accept-new"
    remote: "origin"            # default is 'origin'
    dest: "{{ item }}"
    recursive: yes              # yes is default; being explicit because submodules
    force: yes                  # clobber any locally modified patch files


- name: Create phylesystem-api config file from template
  template:
    src: templates/config.j2
    dest: "{{ phylesystem_api_config_location }}/config.ini"

- name: ensure log directory exists and is writable
  file:
      path: "{{ logfile_dir }}"
      state: directory

- name: ensure phylesystem-api log file exists and is writable
  copy:
    content: ""
    dest: "{{ phylesystem_api_logging_filepath }}"
    force: no

- name: create script directory if not found
  ansible.builtin.file:
    path: "{{ script_location }}/local/bin"
    state: directory
    mode: u=rwx,g=r,o=r

- name: write launch_phylesystem_api.sh script
  template:
    src: templates/launch_phylesystem_api_sh.j2
    dest: "{{ script_location }}/local/bin/launch_phylesystem_api.sh"

- name: "launch launch_phylesystem_api via launch script"
  command: "bash {{ script_location }}/local/bin/launch_phylesystem_api.sh || exit"

