---
deploy_custom_synth: true
deploy_custom_synth_script_fp:
opentree_user: opentree
synth_version: 15.1
ott_version: 3.7.2

# NB - all public APIs move through a common base URL
apis_common_base_URL: https://ot37.opentreeoflife.org
# Some development systems also look to production data
apis_production_base_URL: https://api.opentreeoflife.org

peyotl_otc_ws_branch: master-python-3.12
ws_wrapper_branch: auto-redeploy
ws_dir: /home/{{ansibleuser}}/ws_dir
ot_repo_dir: /home/{{opentree_user}}/repos
chronosynth_branch: dev

