---
# variables for development servers
# Variables set here will override settings in roles/defaults
deploy_custom_synth: true
deploy_custom_synth_script_fp: /home/deploy/repos/ws_wrapper/scratch/deploy_custom_synth.bash
opentree_user: opentree
synth_version: 14.8
ott_version: 3.6

# NB - all public APIs move through a common base URL
apis_common_base_URL: https://ot68.opentreeoflife.org
# Some development systems also look to production data
apis_production_base_URL: https://api.opentreeoflife.org

peyotl_otc_ws_branch: master
ws_wrapper_branch: rebuild-page
ws_dir: /home/{{ansibleuser}}/ws_dir
ot_repo_dir: /home/{{opentree_user}}/repos
chronosynth_branch: dev

treeview_github_app_id: 
treeview_github_client_id: 
treeview_github_redirect_uri: 
treeview_github_app_installation_id: 

default_custom_collection: acaciamulga/fabaceae
default_custom_root_id: 560323
default_custom_taxon_name: Legumes