---
# NOTE that we'll default to safe (dev) values here to avoid disasters on
# production. For staging, production, or other situations, override at the
# host level by creating '{host}.yml` (for example `phylesystemapi.yml`,
# `production.yml`, ...)

# TODO: ditch this web2py stuff,or keep it for curation app?
web2py_git_remote: https://github.com/web2py/web2py.git
web2py_version: 2.19.1
web2py_python_version: python2.7
venv_web2py: venv_web2py
opentree_git_remote: https://github.com/OpenTreeOfLife/opentree
opentree_branch: master

# NB We'll use pip requirements for Pyramid source and version,
# but we still need to specify its python version here
pyramid_python_version: 3.9
venv_pyramid: venv_pyramid

# synth-tree viewer source (Pyramid version)
tree_viewer_git_remote: https://github.com/OpenTreeOfLife/webapp-tree-viewer
tree_viewer_branch: master
tree_viewer_config_location: "/home/{{ansibleuser}}/configs/synthetic_tree_viewer"
# TODO: copy this for pyramid curation app?

# REMINDER: local peyotl is still required!
peyotl_webapp_branch: master

install_location: "{{ ot_repo_dir }}"
# ignore curator for now... maybe always the safer choice?
install_curator: False

script_location: "{{ ws_dir }}"
logfile_dir: "/home/{{ ansibleuser }}/logs"
tree_viewer_logging_filepath: "{{ logfile_dir }}/synth_tree_viewer.log"
