# Copies synthesis tree and taxonomy from local synthesis directory

- name: Copy synth tree from synth_dir to served location.
  copy:
    src: "{{ synth_dir }}/tree_builds/opentree{{ synth_version }}"
    dest: "{{ otc_ws_data }}/synth_trees/"
    remote_src: true
    mode: preserve

- name: Copy OTT from synth_dir to served location.
  copy:
    src: "{{ synth_dir }}/ott/{{ ott_version }}"
    dest: "{{ otc_ws_data }}/"
    remote_src: true
    mode: preserve
