---
# Downloads and unpacks a copy of synthetic tree and OTT into correct
# location for webservices
# Used in cases where synthesis not run locally

- name: Create unpacked_dir
  file:
    path: "{{ unpacked_dir }}"
    state: directory

- name: Create downloads_dir
  file:
    path: "{{ downloads_dir }}"
    state: directory

## download, unpack, and copy OTT
- name: Download OTT
  include_role:
    name: taxonomy
  vars:
    ott_destination_dir: "{{ otc_ws_data }}"

## download, unpack, and copy synthesis tree
- name: Download copy of synth tree from files server
  get_url:
    url: "{{ synth_tree_url }}"
    dest: "{{ downloads_dir }}"
    #creates: "{{ downloads_dir }}/opentree{{ synth_version }}.tgz"

- name: Uncompress synth tree
  unarchive:
    src: "{{ downloads_dir }}/opentree{{ synth_version }}.tgz"
    dest: "{{ unpacked_dir }}"
    creates: "{{ unpacked_dir }}/opentree{{ synth_version }}/index.json"
    remote_src: yes

- name: Copy synth tree from unpacked_dir to ws dir
  copy:
    src: "{{ unpacked_dir }}/opentree{{ synth_version }}"
    dest: "{{ otc_ws_data }}/"
    remote_src: true
    mode: preserve
