---
# task vars
chronosynth_branch: dev
logfile_dir: /home/{{ansibleuser}}/logs
chronosynth_logging_filepath: "{{ logfile_dir }}/chronosynth.log"
install_dir: "/home/{{ansibleuser}}/repos"
chronosynth_config_location: "/home/{{ansibleuser}}/.chronosynth"
