---
- name: Install basic libraries and tools using apt
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - build-essential
    - daemonize  # for otc_tol_ws
    - git-core
    - libapache2-mod-wsgi
    - psmisc  # killall does not come with debian, used by launch_otc_ws_...
    - python-apt
    - python-dev
    - python-pip
    - python3-pip
    - python3-venv
    - python-setuptools
    - rsync
    - unzip
    - virtualenv
  become: true
  become_method: sudo

- name: install apache2 modules that we rely on.
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - proxy
    - proxy_http
    - rewrite
    - ssl
  become: true
  become_method: sudo

- name: Create the directory structure for components, builds, and installations
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{normaluser}}"
    group: "{{normaluser}}"
  with_items:
    - "{{ repo_dir }}"
    - "{{ synth_dir }}"
    - "{{ ws_dir }}"
    - "{{ synth_dir }}/buildotc"
    - "{{ synth_dir }}/installed"
    - "{{ synth_dir }}/ott"
    - "{{ synth_dir }}/ott/{{ ott_synth_full_version }}"
    - "{{ synth_dir }}/in_progress_tree_builds"
    - "{{ synth_dir }}/tree_builds"
    - "{{ ws_dir }}/buildotc"
    - "{{ ws_dir }}/installed"
    - "{{ otc_ws_data }}"
    - "{{ otc_ws_data }}/synth_trees"
  become: true
  become_user: "{{ normaluser }}"

- name: "See if venv_synth virtualenv dir exists"
  stat:
    path: "{{ venv_synth }}/bin/python"
  register: venvsynthpython

- name: "See if venv_otcws virtualenv dir exists"
  stat:
    path: "{{ venv_otcws }}/bin/python"
  register: venvotcwspython

- name: "See if venv_web2py virtualenv dir exists"
  stat:
    path: "{{ venv_web2py }}/bin/python"
  register: venvweb2pypython

- name: "Create python 3 virtualenvs for synthesis."
  command:
    python3 -m venv "{{ venv_synth }}"
  when: (not venvsynthpython.stat.exists)
  become: true
  become_user: "{{ normaluser }}"

- name: "Create python 3 virtualenvs for otc-web-services."
  command:
    python3  -m venv "{{ venv_otcws }}"
  when: (not venvotcwspython.stat.exists)
  become: true
  become_user: "{{ normaluser }}"

- name: "Make sure that python2.7 can use virtualenv"
  command:
    python2.7  -m pip install virtualenv
  become: true
  become_user: "{{ normaluser }}"

- name: "Create python 2.7 virtualenv for web2py-based web services."
  command:
    python2.7  -m virtualenv "{{ venv_web2py }}"
  when: (not venvweb2pypython.stat.exists)
  become: true
  become_user: "{{ normaluser }}"
