---
# python2 might not be installed on server (e.g. Ubuntu16)
- name: Install basic python packages, build tools and git
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - daemonize  # for otc_tol_ws
    - git-core
    - psmisc  # killall does not come with debian, used by launch_otc_ws_...
    - python-apt
    - python-dev
    - rsync
    - virtualenv
  become: true
  become_method: sudo

- name: Create the directory structure for components, builds, and installations
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{normaluser}}"
    group: "{{normaluser}}"
  with_items:
    - "{{ synth_dir }}"
    - "{{ ws_dir }}"
    - "{{ synth_dir }}/buildotc"
    - "{{ synth_dir }}/installed"
    - "{{ synth_dir }}/ott"
    - "{{ synth_dir }}/ott/{{ ott_synth_full_version }}"
    - "{{ synth_dir }}/in_progress_tree_builds"
    - "{{ synth_dir }}/tree_builds"
    - "{{ ws_dir }}/buildotc"
    - "{{ ws_dir }}/installed"
    - "{{ otc_ws_data }}"
    - "{{ otc_ws_data }}/synth_trees"
  become: true
  become_user: "{{ normaluser }}"
