---

- name: Clone propinquity repo
  git:
    repo: "{{ propinquity_git_remote }}"
    dest: "{{ install_location }}/propinquity"
    version: "{{ propinquity_branch }}"

- name: Install propinquity prerequisites into "{{venv_propinquity}}"
  pip:
    requirements: "{{ install_location }}/propinquity/requirements.txt"
    virtualenv: "{{ venv_propinquity }}"
    virtualenv_python: "{{ python_version }}"

- name: Install propinquity into {{venv_propinquity}} as a link
  pip:
    name: "{{ install_location }}/propinquity"
    extra_args: '-e'
    virtualenv: "{{ venv_propinquity }}"
    virtualenv_python: "{{ python_version }}"


- name: Create custom synthesis scratch dir
  file:
    state: directory
    path: "{{ install_location }}/custom_synth_scratch"
    owner: "{{ ansibleuser }}"
    group: "{{ ansibleuser }}"

- name: Create custom synthesis config dir
  file:
    state: directory
    path: "{{ install_location }}/custom_config"
    owner: "{{ ansibleuser }}"
    group: "{{ ansibleuser }}"

- name: Write propinq_ws_env.sh script
  template:
    src: templates/propinq_ws_env_sh.j2
    dest: "{{ install_location }}/custom_config/propinq_ws_env.sh"
