---

- name: Clone propinquity repo
  git:
    repo: "{{ propinquity_git_remote }}"
    dest: "{{ install_location }}/propinquity"
    version: "{{ propinquity_branch }}"

- name: Install propinquity prerequisites into "{{venv_propinquity}}"
  pip:
    requirements: "{{ install_location }}/propinquity/requirements.txt"
    virtualenv: "{{ venv_propinquity }}"
    virtualenv_python: "{{ python_version }}"

- name: Install propinquity into {{venv_propinquity}} as a link
  pip:
    name: "{{ install_location }}/propinquity"
    extra_args: '-e'
    virtualenv: "{{ venv_propinquity }}"
    virtualenv_python: "{{ python_version }}"


- name: Create custom synthesis scratch dir
  file:
    state: directory
    path: "{{ install_location }}/custom_synth_scratch"
    owner: "{{ ansibleuser }}"
    group: "{{ ansibleuser }}"

- name: Create custom synthesis config dir
  file:
    state: directory
    path: "{{ install_location }}/custom_config"
    owner: "{{ ansibleuser }}"
    group: "{{ ansibleuser }}"

- name: Write propinq_ws_env.sh script
  template:
    src: templates/propinq_ws_env_sh.j2
    dest: "{{ install_location }}/custom_config/propinq_ws_env.sh"

- name: Download OTT
  include_role:
    name: taxonomy
  vars:
    ott_destination_dir: "{{ install_location }}/ott"

- name: "Create {{ install_location }}/phylesystem/shards for phylesystem and collections data"
  file:
    state: directory
    path: "{{ install_location }}/phylesystem/shards"
    owner: "{{ ansibleuser }}"
    group: "{{ ansibleuser }}"

- name: "Clone studies repo from {{ phylesystem_remote }}"
  git:
    repo: "{{ phylesystem_remote }}"
    dest: "{{ install_location }}/phylesystem/shards/{{ phylesystem_repo }}"
    version: master


- name: "Clone collections repo from {{ collections_remote }}"
  git:
    repo: "{{ collections_remote }}"
    dest: "{{ install_location }}/phylesystem/shards/{{ collections_repo }}"
    version: master


- name: "Clone script-managed-trees repo"
  git:
    repo: "https://github.com/OpenTreeOfLife/script-managed-trees"
    dest: "{{ install_location }}/script-managed-trees"
    version: master

- name: Write propinq_config.json script
  template:
    src: templates/propinq_config_json.j2
    dest: "{{ install_location }}/custom_config/propinq_config.json"
